config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  get 'tweets/index'
  get 'tweets/new'
  # resources :users
  
  # get 'users/index'
  # get 'users/new'
  
  root 'tweets#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    # belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    # has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/top_controller.rb
class TopController < ApplicationController
end

app/controllers/tweets_controller.rb
 class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
    @tweet = Tweet.new
  end
  
  def create
    tweet = Tweet.new(message: params[:tweet][:message])
    tweet.save
    redirect_to root_path
  end
  
  def destroy
    Tweet.find(params[:id]).destroy
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class tweetsController < ApplicationController
  def index
    @tweets = tweet.all
  end

  def new
    @tweet = tweet.new
  end
  
  def create
    tweet = tweet.new(uid: params[:tweet][:uid], pass: params[:tweet][:pass],age: params[:tweet][:age])
    tweet.save
    redirect_to root_path
  end
  
  def destroy
    tweet.find(params[:id]).destroy
    flash[:success] = "ツイートを削除しました"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L5</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/index.html.erb
<% @tweets.each do |e| %>
    <p>
    <%= e.message %>
    <%= link_to "削除", tweet_path(e), data: { "turbo-method": :delete } %>
    </p>
<% end %>
<hr>

<%= form_for @tweet, url: {action: :create} do |f| %>
    <%= f.label :message, 'message' %>
    <%= f.text_field :message %><br>
    <%= f.submit 'ツイート' %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |e| %>
    <p>
    UID <%= e.uid %>
    Pass <%= e.pass %>
    Age <%= e.age %>
    <%= link_to "削除", user_path(e), data: { "turbo-method": :delete } %>
    </p>
<% end %>

<%= link_to "新規追加", users_new_path %>

app/views/users/new.html.erb
<%= form_for @user, url: {action: :create}  do |f| %>
    <%= f.label :uid, 'UID' %>
    <%= f.text_field :uid %><br>
    <%= f.label :pass,'Pass' %>
    <%= f.password_field :pass %><br>
    <%= f.label :age, 'Age' %>
    <%= f.text_field :age %><br>
    <%= f.submit '登録' %>
<% end %>